salesforce/Argus

README.md

There's a small but annoying error in the README.md.

It's => Its because English Grammar

---

ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/DownsampleTransform.java
ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/DownsampleTransformTest.java

fixed a bug that was originally in Downsample transform.
In this bug, when a metric{tag=*} includes multiple Time series and one of them is empty, DOWNSAMPLE(metric{tag=*},$1h-avg) will raise an exception when calculating window_start. This pull request fixed that bug.

fixed a bug that was originally in Downsample transform

---

ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/DefaultTSDBService.java
ArgusCore/src/test/java/com/salesforce/dva/argus/AbstractTest.java
ArgusCore/src/test/resources/log4j.properties

Make the logging for when a metric isn't found in TSDB to warn as it's normal for this to occur when trying to fetch the UID for an annotation time series upon the first write to it.

Update to remove zookeeper log spew from integration tests.

---

ArgusWeb/app/js/config.js
ArgusWeb/app/js/directives/controls/date.js
ArgusWeb/app/js/services/dashboard.js

- Disable GMT option when offset is used for agDate input.
- Update URL param such that " GMT" is added to URL properly when GMT is used for agDate. Existing links will work normally without GMT checkbox being checked. This does not apply to offset input for agDate
Existing link with no GMT:
New link with GMT:

GMT Option Bug Fix

---

ArgusWeb/app/js/directives/charts/d3LineChartTest.js
ArgusWeb/app/js/directives/charts/lineChart.js
ArgusWeb/app/js/templates/charts/topToolbar.html

- Add checkbox to toggle on log10 base scale for chart's y Axis (only in /d3test)
- Add limit for zoom scale
- Dynamically enable the time toggle buttons (1h/1d/1w/1m/1y)

more D3 Line Chart improvement 

---

ArgusWeb/app/js/controllers/main.js

With this change, dashboard and alert query calls can be trigger by refreshing the browser tab as well.

Enable dashboard and alert lists reload with page refresh

---

ArgusWeb/app/js/controllers/alerts.js
ArgusWeb/app/js/controllers/dashboards.js
ArgusWeb/app/js/controllers/main.js

1. Allow browser refresh to trigger API query call for dashboard/alert lists.
2. Show loading spinner after the reload button is pressed.
3. Prevent tab switching within dashboard list when reload button is pressed.
All of the above are in the develop branch as well.

A few UI hot fixes (resubmission)

---

ArgusWeb/app/js/config.js
ArgusWeb/app/js/directives/charts/chart.js
ArgusWeb/app/js/directives/charts/lineChart.js
ArgusWeb/app/js/templates/charts/topToolbar.html

1. Fix the issue of mouseover circles placed outside of the container.
2. Move x-axis tag (time) to the top of the graph.
3. Sort sources in legend alphabetically.
4. Remove time value in the tooltip.
5. Add sorting by value feature for tooltip items.
6. Add detail tooltip option, which displays source names and more precision for data values.

Tooltip Update

---

ArgusWeb/app/js/directives/charts/lineChart.js
ArgusWeb/app/js/templates/charts/topToolbar.html

The problem is caused by return before setting graphRendered to true. But I will delete it right now because it is not working when the chart is being rendered. The spinner will just stop spinning anyway. Example: http://localhost:8080/argus/#/dashboards/464709?
I guess d3 might send some callback to get every pixel rendered on page. Therefore, setting graphRendered to true it after some d3 call makes no sense.
Will work on optimizing the datapoints rendering instead to make the render time neglectable.

Fix endless loading spinner when graph is empty issue

---

ArgusWeb/app/js/directives/charts/lineChart.js

- Fix rendering error when a path is outside scope
- Render only data within the time domain in path element (rely on clip-path before)

Render only data within the time domain in path element and small fix

---

ArgusCore/src/main/java/com/salesforce/dva/argus/system/SystemInitializer.java

Issue #342 : This should allow us to use the same built war in multiple environments by specifying the database connection properties at runtime.

Allow overriding of jpa properties by using system.property.jpa prefix

---

ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/HoltWintersAnalysis.java
ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/HoltWintersTransformTest.java

I could see two ways to solve #336 , but I wasn't sure which one would work better with the rest of the system.
1. (the one implemented in this branch).  The HoltWintersTransform always uses US locale for its outupt
2. HoltWintersTransform uses the same locale and format for parsing its input data and returning its output data.
Which do you think is better?  I think I like number 2, but I was afraid that other parts of the system might be assuming the output was in US locale.

Issue #336 - HoltWintersAnalysis always uses US locale

---

pom.xml

Set the maven-compiler-plugin to 3.6.0 to avoid compiler errors in #323

Issue #323 set maven-compiler-plugin version

---

ArgusWeb/app/js/directives/charts/lineChart.js

For some dashboard, the metric embedded in the markup should define the time range rather than the ag-date. So just use the response data's date range right now for a quick solution.

Temporary fix for the date range issue

---

ArgusCore/pom.xml

exclude jersey based dependencies from phoenix dependency.

update argus-core pom.xml

---

ArgusWeb/app/css/main.css
ArgusWeb/app/js/directives/charts/lineChart.js
ArgusWeb/app/js/templates/modals/chartOptions.html

Chart updates upon selection inside modal and includes functionality for:
- Date formats
- Y-axis tick format and # (X axis options have been removed)
- Truncation options for metric name displayed in Legend.  Tooltip still needs setup
- Downsampling options
- Brushing & Zooming options
- Tooltip sorting
- Display raw data for datapoint value (tooltip)
- Custom format for datapoint value (tooltip)
Still outstanding:
- Color palette options
- Move Synchronize options to modal
- Apply settings to all graphs
- Reset to default settings

updates for chart options

---

ArgusWeb/package.json

causes error when running webpack for deployment.

roll back version of chunk manifest webpack plugin

---

ArgusWeb/app/js/templates/headerMenu.html

Once Metric Discovery service is working again, can add tab back to header.

remove BETA tab from header

---

ArgusWeb/app/js/controllers/viewMetrics.js
ArgusWeb/app/js/directives/agInfiniteScroll.js
ArgusWeb/app/js/directives/charts/chart.js
ArgusWeb/app/js/directives/charts/lineChart.js
ArgusWeb/app/js/directives/controls/dashboard.js
ArgusWeb/app/js/directives/controls/date.js
ArgusWeb/app/js/services/charts/chartElements.js
ArgusWeb/app/js/services/charts/chartTools.js
ArgusWeb/app/js/templates/charts/topToolbar.html
ArgusWeb/app/js/templates/modals/chartOptions.html
ArgusWeb/app/js/templates/viewmetrics.html

- Add an option to view charts in local time instead of GMT (independent from agDate option)
- Fix the bug of checking if a metric is in the domain incorrectly
- Fix the bug of annotation label stuck on the page after click-to-stay
- Display both local time and GMT in annotation label

Add local time zone view support and a few bug fixes

---

ArgusClient/src/main/java/com/salesforce/dva/argus/client/MetricCommitter.java
ArgusCore/pom.xml
ArgusCore/src/main/java/com/salesforce/dva/argus/entity/KeywordQuery.java
ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Metric.java
ArgusCore/src/main/java/com/salesforce/dva/argus/entity/MetricSchemaRecord.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/SchemaService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/HoltWintersDeviation.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/HoltWintersForecast.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AbstractSchemaService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/DefaultDiscoveryService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/MetricSchemaRecordList.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/DefaultTSDBService.java
ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/AbstractSchemaServiceTest.java
ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/entity/MetricDiscoveryQuery.java
ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/entity/MetricSchemaRecord.java
ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/DiscoveryServiceTest.java
ArgusSDK/src/test/resources/DiscoveryServiceTest.json
ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/dto/MethodHelpDto.java
ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/dto/MetricDiscoveryQueryDto.java
ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/dto/NamespaceDto.java
ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/DiscoveryResources.java

Advantages of using ES rest client:
- minimal dependencies
- load balancing across all available nodes
- failover in case of node failures and upon specific response codes
- failed connection penalization (whether a failed node is retried depends on how many consecutive times it failed; the more failed attempts the longer the client will wait before trying that same node again)
- persistent connections
- trace logging of requests and responses
- optional automatic discovery of cluster nodes
@rajsarkapally-sfdc @dilipdevaraj-sfdc

Use ElasticSearch RestClient instead of vanilla httpclient (Merge into 2.9.0)

---

ArgusCore/pom.xml
ArgusSDK/pom.xml
ArgusWebServices/pom.xml
pom.xml

To fix #673: Addressing some security vulnerabilities in dependency versions and moving version declaration to the parent POM's `dependencyManagement` section.
* CVE: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-5929
* CWE: https://cwe.mitre.org/data/definitions/502.html
* Found at https://snyk.io/vuln/SNYK-JAVA-CHQOSLOGBACK-30208
* CVE: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-7525
* CWE: https://cwe.mitre.org/data/definitions/502.html
* Found via https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31507, https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31519, https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31520
* CWE: https://cwe.mitre.org/data/definitions/23.html
* Found in https://snyk.io/vuln/SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-31517

Dependency security updates

---

ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/FillCalculateTransform.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/FillTransform.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AbstractSchemaService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/DefaultDiscoveryService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/AbstractTSDBService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/DefaultTSDBService.java
ArgusCore/src/main/javacc/MetricReader.jj
ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/FillTransformTest.java
ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/DashboardResources.java

PR contains following changes:
- FILL Transform bug fix when a metric expression returns empty datapoint set. Also add the ability to distinguish between FILL(expr, #constants#) and FILL(#constants#) by adding a constantsOnly flag
-  Cleanup ESSchemaService exception handling and logging. Also remove records from TRIE if an exception occurs while indexing schema records
- Increase DefaultDiscoveryService schema records fetch size from 500 to 10000.

Refactor ESSchemaService and FILL Transform bug fix

---

ArgusWeb/app/js/argus.js
ArgusWeb/app/js/directives/controls/compute.js
ArgusWeb/app/js/directives/controls/dashboard.js

This is an invisible control, it can watch for a value from another
control and apply some transformation to it.
Scenario:
The same text is used in different parts of a metric name but
in some cases it should be in upper case and in some cases it should
be in lower case. For example we query a metric: `some.namespace.FOO:metric.name-foo`
To build an expression we can define 2 parameters: `my_param` is a dropdown in uppercase and `my_param_ls` is an invisible compute parameter. It takes value of the `my_param` and 
converts it to a lower case:
```
<ag-select name="my_param" label="Very important parameter" default='FOO'>
<option value="FOO">FOO</option>
<option value="BAR">BAR</option>
<option value="BAZ">BAZ</option>
</ag-select>
<ag-compute name="my_param_lc">{{my_param | …
```

Add ag-compute control.

---

ArgusWeb/app/js/services/charts/chartRendering.js

This is a small fix, but I found that status indicator with a visible number field is more readable with this formatting on values > 1000 and especially on numbers > 1M

Print number in a status indicator as a string formatted according to a current locale. Helps to read big numbers

---

ArgusCore/pom.xml

This should fix the `java.lang.ClassCastException: org.slf4j.impl.Log4jLoggerAdapter cannot be cast to ch.qos.logback.classic.Logger` error that happens when you run webservices locally (documented as a common error in the internal "Setting Up Argus Dev" document)

Fix conflicting logger implementations error

---

.travis.deploy.sh

@dilipdevaraj-sfdc This fixes the issue where .travis.deploy.sh couldn't properly source other scripts/files. I tested this out in a separate repo here: https://github.com/justinharringa/travis-source/commits/master

Switch from source -> .

---

.travis.deploy.sh

Javadoc is required for pushing to [Maven Central](https://central.sonatype.org/pages/requirements.html). 
[Skip all docker goals](https://github.com/spotify/docker-maven-plugin#bind-docker-commands-to-maven-phases) to disable push to docker.io. There are currently no credentials set up to push the docker images so this stops pushing to avoid failure when pushing to docker.io.
Note also that the [docker-maven-plugin has been deprecated](https://github.com/spotify/docker-maven-plugin#status-bug-fix-only)
(includes 60a8122 to remove javadoc generation to avoid merge conflicts in release branch and master)

Javadoc required turn off docker deploy

---

ArgusCore/src/main/java/com/salesforce/dva/argus/entity/ScopeOnlySchemaRecord.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/MonitorService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AbstractSchemaService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AsyncHbaseSchemaService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ScopeOnlySchemaRecordList.java
ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/AbstractSchemaServiceTest.java

Have separate bloom filter for scope names only
Remove async put from ElasticSchema Service. ES writes will be synchronous only
Make number of shards, replication factor, scope index name, scope type name configurable

Add new scopenames index with scope and mts field

---

ArgusWeb/app/css/main.css
ArgusWeb/app/index.html
ArgusWeb/app/js/controllers/dashboardsDetail.js
ArgusWeb/app/js/controllers/viewElements.js
ArgusWeb/app/js/directives/charts/metric.js
ArgusWeb/app/js/services/charts/dataProcessing.js
ArgusWeb/app/package-lock.json
ArgusWeb/app/package.json
ArgusWeb/webpack_index.html

**Changes to the markup editor**
1. Add code folding.
2. Highlight matching tags.
3. Extend the editor height to show the entire markup.
4. Fullscreen mode. To enter fullscreen, press: `Ctrl-Alt-F`. To exit fullscreen press: `Esc`.
5. Autocomplete with some HTML, CSS, and Javascript code. To trigger autocomplete, press `Alt-Space`.
6. Autocomplete matching tags.
7. Syntax highlighting for CSS and Javascript code as well.
**Changes to ag-metric**
1. `hideTags` attribute to hide tags. Set it to true to hide all tags in the tooltip and legend of that chart. Set it to comma separated values to hide a few tags. 
2. `hideScope` and `hideMetric` attribute to hide scope values and metric values correspondingly in tooltip and legend.

Update dashboard markup editor and add attribute to ag-metric

---

pom.xml

In maven-javadoc-plugin 3.0.0 they removed additionalparam and made a
proper doclint configuration property
See: https://issues.apache.org/jira/browse/MJAVADOC-474

javadoc plugin 3.0.0 -> use new doclint config

---

pom.xml

This will make it so you have to explicitly tell the docker-maven-plugin to activate (see [the doc](https://github.com/spotify/docker-maven-plugin/tree/v0.4.11#bind-docker-commands-to-maven-phases))

Unbind docker-maven: no automatic build/push

---

ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Alert.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/AlertService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/AlertsCountContext.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java
ArgusCore/src/test/java/com/salesforce/dva/argus/service/AlertServiceTest.java
ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/AlertResources.java

Part 2 of alerts pagination. 
This PR adds search capability to paginated alerts APIs. 
**The APIs being updated in this PR has no caller yet, thus this PR does not affect any existing functionality**
- Unit tests added. 
- Manually tested the APIs with experimental UI changes on my local machine. 
TODO
Part 3: UI changes to hook up alerts and search with new APIs.

Part 2: paginated APIs to search alerts filter on alertname or owner name

---

ArgusCore/src/main/java/com/salesforce/dva/argus/service/mq/kafka/KafkaMessageService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/mq/kafka/Producer.java

Some ArgusCore-dependent modules (eg. ArgusClient) may not need the specific producer or consumer component of MQService. Before, even if the `Producer.java` class was unused, it would initiate a KafkaProducer connection to brokers; this prevents that if disable option is set to true

Options to disable MQService producer or consumer

---

ArgusCore/src/main/java/com/salesforce/dva/argus/service/monitor/CounterMetricJMXExporter.java

JMX exporter program treat all metrics as type=Counter, and if user add another tag called "type" then we will create an invalid MXBean object for JMX.  Here I choose to escape the "type" tag
This issue may affect exporting certain matrix through JMX, but it does not affect anything else.  The exceptions are handled
This is a hotfix.
@naveenreddykarri 
@colbyguan

Fix the potential invalid objectname due to metric tags contain "type" key

---

update-version

Couldn't find a way to do multiline-regex with `sed`, and figuring out a Maven way of doing it would have taken much longer, so here is a Python script. It works like this:
Intended to work on both Python 2 and 3. Tested with versions:
* `2.7.15`
* `3.6.3`
Checks user inputs for proper format

Script that helps update all version numbers (POM and RPM) when doing releases

---

ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java
ArgusCore/src/main/java/com/salesforce/dva/argus/service/monitor/CounterMetricJMXExporter.java

Avoid the possibility that user use tag that conflict with the build-in keywords of the exporter
This is tested in shared2-argusalertdev1-1-prd.eng.sfdc.net
@sundeepsf 
@naveenreddykarri

fix the keyword conflicts in JMX exporter
