ArgusWeb/README.md
Updates to the ArgusWeb README.  More complete notes for the install and build for a new user.
=> Update README with latest setup & install procedures.

ArgusWeb/README.md, ArgusWeb/app/css/main.css, ArgusWeb/app/index.html, ArgusWeb/app/utils/autoFocus.js, ArgusWeb/app/views/alerts/alert-detail.html, ArgusWeb/app/views/alerts/alert-list.html, ArgusWeb/app/views/argus_custom_directives/argus-controls.js, ArgusWeb/app/views/dashboards/dashboard-detail.html, ArgusWeb/app/views/dashboards/dashboard-list.html, ArgusWeb/app/views/dashboards/dashboards.js, ArgusWeb/app/views/login/login.html, ArgusWeb/app/views/namespace/namespace.html, ArgusWeb/app/views/viewmetrics/viewmetrics.html
Also added a new directive to autofocus to input fields, such as the Login view, to benefit the accessibility and usability of the username field, and allow the user to easily start typing without having to use the mouse to focus the field before typing.
Other updates include minor tweaks to html & css settings to normalize the layout, headings, spacing, alignment, etc.  More updates of this type will be coming in the future, including splitting up headers, tabs, etc. into separate directives to help keep templates more consistent across the site.
=> Minor UI updates to code base, templates, headings, etc.

ArgusWeb/app/css/main.css, ArgusWeb/app/index.html, ArgusWeb/app/js/argus.js, ArgusWeb/app/js/config.js, ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/directives/charts/d3LineChart.js, ArgusWeb/app/js/templates/viewmetrics.html, ArgusWeb/bower.json
Should work for multiple lines. Changed mouseover tooltip to not follow the mouse but rather stay in the same place. 
Example usage is in Metrics tab, select "Use D3"
=> Base D3 line chart directive

ArgusWeb/app/views/alerts/alert-detail.html
short term fix to help users identify triggers to assign to a notification.
=> hot fix to multi-select for assigning triggers to notifications.

ArgusWeb/app/js/directives/charts/chart.js
Just a test to check if PR works for me.
=> Test for PR

ArgusWeb/app/views/argus_custom_directives/argus-controls.js, ArgusWeb/app/views/main/main.js
- automatically add control params to url when dashboard loads.
- allow the user to update the local scope of controls, and also update params in the url.
=> Parametrized Url updates

ArgusWeb/app/views/argus_custom_directives/argus-viewelements.js
Should have caught this myself after moving the method to the DashboardService.
=> fix bug for W-3318644 - ag-flags broken.

ArgusCore/src/main/java/com/salesforce/dva/argus/service/AuthService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/MonitorService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/auth/LDAPAuthService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/auth/NoAuthService.java
Updated to track mau/dau based on duration of entries.
@SalesforceEng/argus please review
=> Add tracking of daily and monthly users.

ArgusWeb/app/js/controllers/alerts.js, ArgusWeb/app/js/templates/alert-list.html, ArgusWeb/app/js/templates/dashboard-list.html
Add loading icon and sorting feature to the alert page
=> Alert View Page Enhancement 

ArgusWeb/app/index.html, ArgusWeb/app/js/directives/ngEnter.js, ArgusWeb/app/js/templates/viewmetrics.html
Metrics expression can be entered now by pressing enter key.
=> Link Enter Key with "Go!" Botton on Metrics Page

ArgusWeb/app/js/argusConfig.js, ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/directives/controls/dashboard.js, ArgusWeb/app/js/services/controls.js
=> merge Pimengs PR for url parameterization to metrics view.

ArgusWeb/app/css/main.css, ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/templates/viewmetrics.html
add search icon, toggle between views of metric discovery and graph/chart, add loading spinner, fix minor rendering issues regards to graph not extending full width.
=> More UI updates for Metrics

ArgusWeb/app/js/templates/tableList.html
- Corrected total number message dialog
- Disabled sort feature on state column
=> Minior UI change

ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/services/search.js, ArgusWeb/app/js/templates/viewmetrics.html
add buttons to clear, add expression, graph expression.
=> Metric Discovery UI updates

ArgusWeb/app/js/directives/tableList.js, ArgusWeb/app/js/templates/alert-list.html, ArgusWeb/app/js/templates/dashboard-list.html, ArgusWeb/app/js/templates/tableList.html
Delete the dashboard/alert count message when the spinner is showing during loading.
=> Remove message dialog appearance during loading

ArgusWeb/app/js/controllers/alerts.js
Fix the bug that loading spinner is not showing for the alert page when alerts are loading.
=> fix alerts query wait/loading issue

ArgusWeb/app/js/services/dashboard.js
Did not properly merge 2.0 into master.
=> Fix for ag-flags

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/d3LineChartTest.js
Use url: http://localhost:8080/argus/#/d3test to see the effects.
=> Minor changes on cursor&crossline style; add grid to the line chart

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/d3LineChartTest.js
Still, use http://localhost:8080/argus/#/d3test to check it locally.
Will work on the styles and layout later.
=> add brush, zoom, pan feature to d3chart.

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/d3LineChartTest.js
-Add new time toggle buttons
-refine some codes on brush&zoom
-fix the brush&zoom/pan not syncing correctly bug
=> Add new time toggle buttons

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/d3LineChartTest.js
- Add yAxis rescaling with xAxis when zooming/brushing/paning feature
- Fix brush area xAxis not showing correct problem
=> Add yAxis rescaling and fix some minor bug

ArgusWeb/app/js/directives/charts/d3LineChartTest.js
The xAxis tick is behaving strangely by adding new ticks as in brush area axis. 
Will fix that next.
=> add resize feature, brush status will remain after resize

ArgusWeb/app/js/directives/charts/d3LineChartTest.js
- Fix chart showing extra ticks when resizing bug.
- Fix bug of grid not syncing with axis when rescaling.
- Add checkbox for brush view display
- Add checkbox for mouse wheel zoom
=> Fix bug of chart showing extra ticks when resizing & Add checkbox for brush display and mouse wheel zoom

ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/DownsampleTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/FillTransform.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/FillTransformTest.java, ArgusWeb/app/js/controllers/dashboardsDetail.js
I modified test cases as well.
=> Add snapping to fill transform when it generates a constant line

ArgusWeb/app/js/config.js, ArgusWeb/app/js/controllers/alerts.js, ArgusWeb/app/js/controllers/alertsDetail.js, ArgusWeb/app/js/services/factories/alerts.js, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/dto/AlertDto.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/AbstractResource.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/AlertResources.java
- New GET API call for the alert list (/alerts/meta). It returns all alerts with empty expressions, triggers, and notifications.
- SessionStorage for the alert list. The reload button, editing an alert in its particular page with saving, and open a new browser tab can trigger a new API call for alert list.
=> Alert Loading Enhancement

ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/system/SystemConfiguration.java, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js
X axis now can display local time or GMT based on user's input value in agDate.
=> Add time domain to x axis

ArgusWeb/app/index.html, ArgusWeb/app/js/argus.js, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/dateHandler.js
1. Factor out the date handling code into a service.
2. Update the date range label to show time zone information.
3. Set different color for different line graphs
=> Add color support and refactor date handling code

ArgusWeb/app/js/directives/charts/lineChart.js
- Fix an issue that the circle points on line do not sync when zooming/panning on the chart.
- Fix some problems caused by last changes.
=> Minor fixes on d3 linechart

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/charts/topToolbar.html
moved chart rendering to directive's controller.
add menu for date controls.
display legend and update on hover.  (still needs rework to display on page load)
fix bug to toggle mouse scroll and other bug fixes.
merged previous changes.
=> Updates to chart toolbar.

ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/DiscoveryService.java, ArgusSDK/src/test/resources/DiscoveryServiceTest.json
=> fix discovery service sdk constant

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/charts/topToolbar.html
- Make time brush focus on the previous center when click time toggle
- Select the button by name instead of id (prepare for the multi-chart DOM manipulation)
- Move DOM modification to link function
- Move the crosslineTooltip info to X & Y Axis
=> More improvements & changes on d3 linechart

ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/dataProcessing.js, ArgusWeb/app/js/templates/charts/topToolbar.html
- Click graph name in the legend to toggle it on and off
- Hiding others feature is supported as well
- Once a graph is hidden, its name will turn gray in the legend (this is a little bit slow and laggy. Maybe @cnardi-dev can help?)
=> Use legend to toggle graph on and off

ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/DiscoveryService.java, ArgusSDK/src/test/resources/DiscoveryServiceTest.json, ArgusWeb/app/css/main.css, ArgusWeb/app/js/controllers/dashboards.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/charts/topToolbar.html
see the TODOs in the comments.  know issues:
- x position of annotation is not syncing with x axis (also update on panning/zooming)
- need to calc offset to position for multiple annotations
- text field is too large and can't be used.  need alternate way to inspect/copy description
=> render Annotation as flag. Merging from develop branch.

ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/charts/topToolbar.html
- refactor the mouse over circle code 
- add graphClassName to each metric to bind all the graph elements together under one class
=> Finished graph toggling feature

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/charts/topToolbar.html
- Fix some minor issues.
- Refine some codes
- Move the crosslineTooltip info to X & Y Axis and add some styles.
- Implement main chart brush and add checkbox for it.
- Fix the issue that y domain does not include some datapoints
- Fix an issue that full brush will show when resizing
=> Cross line tooltip and main chart brush feature

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/lineChart.js
- Change color scheme to support 20 colors.
- Create new column when there are 8 items in the tooltip.
- Fix empty data bug for tooltip and brush (rescaleY), by not creating the element initially.
=> Minor tooltip enhancement and fix some empty data set issue

ArgusWeb/app/css/main.css, ArgusWeb/app/js/templates/charts/topToolbar.html
=> styling updates

ArgusWeb/app/js/directives/charts/lineChart.js
Added todo to determine solution and if multiple series w/flag data is possible.  If so, what is the offset so markers don't stack on top of each other.
=> fix undefined showing in console

ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/inputTracker.js
- Display a message when nothing is returned from TSDB or the expression does not exist.
- Show local timezone information in the time range label.
=> Some Empty Dataset Handling

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js
- Fix y axis does not render negative value issue
- Fix the issue that chart with full width is only rendered by half when chart with half width co-exists
- Fix the issue of negative width when nagivate out&back by button on dashboard detail page
=> D3 line chart minor fixes 

ArgusWeb/app/js/directives/charts/lineChart.js
Change elements related to width change only.
=> Add a more precise resize function

ArgusClient/README.md, ArgusCore/README.md, ArgusWeb/app/js/config.js, ArgusWeb/config/development.json, ArgusWeb/config/local.json, ArgusWeb/config/production.json, ArgusWebServices/README.md, README.md, pom.xml
=> Update references to old salesforceEng/Argus github project.

ArgusWeb/app/js/controllers/dashboardsDetail.js, ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/directives/breadcrumbs.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/breadcrumbs.js, ArgusWeb/app/js/templates/charts/topToolbar.html
- Add 'use strict' to prevent some strange behavior of breadcrumbs redirect.
- Remove metrics that cannot be graph from series prior to generating the chart.
=> Breadcrumbs & empty data check enhancement 

ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/charts/topToolbar.html
- Fix menu option storage abnomality and date range not updating issues (caused by chartId naming)
- Fix toggle wheel button acting adversely bug
=> Minor fixes on d3 linechart on menu option storage, date range and toggle wheel

ArgusWeb/app/js/directives/charts/chart.js
$promise + closure = doh!
When more time is available, should refactor further: 
- move api calls to service which will return data inside $promise with closure.  This will avoid having to call another method with many params to create closure.
Refer to "js/services/teams.js" in the Driven project for solid example.
=> fix bug: seriesname and seriescolor

ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/charts/topToolbar.html
- Fix the bug of only one dashboard loads when there are multiple dashboards with different series names (metricCount did not decrement correctly).
- Fix the problem empty graph message resizing issue.
=> Multiple series names dashboards not loading bug fix

ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js
- show full date range user defined in chart
- fix chart not showing chart title
=> D3 show full date range user defined in chart & fix chart not showing chart title

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/charts/topToolbar.html
Empty returned metrics error message was not displaying because it was not added to the series to pass into graph rendering.
=> Misplacement of series appending.

ArgusWeb/app/js/directives/charts/lineChart.js
Fix the graph (lines/circles/tip) remaining issue when brush into empty date range.
=> D3 Fix on brushing/zooming into empty date range issue.

ArgusWeb/app/index.html, ArgusWeb/app/js/argus.js, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/dataProcessing.js, ArgusWeb/app/js/services/jsonUnflatten.js, ArgusWeb/app/js/templates/charts/topToolbar.html
- process agOption into a json file
- Support title and subtitle with styles, x and y axis labels, chart height and chart width from agOptions.
=> agOption supprot

ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/dataProcessing.js, ArgusWeb/app/js/services/charts/dateHandler.js, ArgusWeb/app/js/templates/viewmetrics.html
- d3 will be used to draw charts instead of highchart for metric view page
- Annotations/flag do not work at the moment
=> Use d3 directive for metric view page

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/templates/charts/topToolbar.html
GIT had merging issues and the previous commits for chart.js should be reviewed to ensure it is in sync.
=> minor updates to chart, smallChart css, statusIndicator display.

ArgusClient/pom.xml, ArgusClient/src/main/java/com/salesforce/dva/argus/client/ClientServiceFactory.java, ArgusCore/pom.xml, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/HoltWintersAnalysis.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricFilterWithInteralReducerTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AsyncHbaseSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/system/SystemInitializer.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/HoltWintersTransformTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/SortTransformTest.java, ArgusSDK/pom.xml, ArgusWeb/app/js/templates/charts/topToolbar.html, ArgusWebServices/pom.xml, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/filter/PerfFilter.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/AlertResources.java, pom.xml, src/main/resources/META-INF/logback.xml
making sure my new laptop is working ok.
=> testing new settings.

ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/charts/topToolbar.html
update small chart to show date, menu options and reset.
=> fix broken menu links from nested ng-if conditions.

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/lineChart.js
prevent charts from unwanted wrapping.
=> Update font size for chart title to match production.

ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/directives/charts/lineChart.js
Fix tooltip issue after toggling some sources off (W-3635998) and Empty returned annotation (W-3636019)
=> Fix two production bug

ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/services/charts/dataProcessing.js
'event' is undefined in console, causes JS exception and no charts render.  'even't is not utilized or consumed even though it's being passed through methods.  Removing altogether.
=> Firefore bug fix for: W-3638239

ArgusWeb/app/css/main.css, ArgusWeb/app/index.html, ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/dataProcessing.js, ArgusWeb/bower.json, pom.xml
- Render multiple series' annotations in metric view page
- Change color of annotations to their series' color and allow annotations to be toggled off using legend
- Add mouse over label to annotation
=> More support for annotation

ArgusWeb/app/js/services/charts/dataProcessing.js
When I initially pushed these changes, this functionality was in /services/dashboard.js file. Now it has been moved to /services/charts/dataProcessing.js. Hence resubmitting the PR with those changes.
=> Ability to subtract time from parameterized data controls.

ArgusWeb/app/js/controllers/alerts.js, ArgusWeb/app/js/services/factories/alerts.js
Add PR #412 to 2.4.1 release branch
=> Cherry Pick "use differernt API endpoint for shared and user's personal alerts"

ArgusWeb/Gruntfile.js, ArgusWeb/config/development.json, ArgusWeb/config/integration.json, ArgusWeb/config/qa.json
- Add qa.json and integration.json for more grunt replace options
- Update version number
=> update UI build package for more grunt options

ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Notification.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/AuditNotifier.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/EmailNotifier.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/GOCNotifier.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/GusNotifier.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/DefaultAlertServiceTest.java
1. Improve History/logging messages.
2. Hash the String key when storing the mappings for cooldownExpirationByTriggerAndMetric and activeStatusByTriggerAndMetric.
=> Improve logging and history messages.

ArgusWeb/app/js/config.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/dateHandler.js
- More precision on d3 Y axis (3 digits instead of 2)
- Fix the bug of fail to obtain start and end time when there is an empty metric in the series 
- Change download data file's name to chart's title
=> A few minor updates and bug fixes

ArgusWeb/app/js/controllers/alerts.js, ArgusWeb/app/js/controllers/dashboards.js, ArgusWeb/app/js/services/tableListService.js
Fix the bug of privileged users not able to see or change other people's private dashboards and alerts. Those items will appear in the user's tab.
=> Fix privileged users alerts and dashboard viewing issue

ArgusWeb/app/js/directives/charts/statusIndicator.js, ArgusWeb/app/js/services/charts/chartRendering.js
Bugs of status indicator which were fixed on master #440
=> Merge hot fixes back to develop

ArgusWeb/app/js/controllers/dashboards.js, ArgusWeb/app/js/controllers/dashboardsDetail.js, ArgusWeb/app/js/directives/tableList.js, ArgusWeb/app/js/templates/dashboard-detail.html, ArgusWeb/app/js/templates/dashboard-list.html, ArgusWeb/app/js/templates/tableList.html
- Add a clone button in the dashboard list page to clone a dashboard
- Add a clone button in the markup page in dashboard detail page
=> Add Dashboard clone feature in UI

ArgusWeb/app/js/templates/dashboard-detail.html
- also updated copy text on Clone button.  Will replace this with new Trooper icon!
=> bug fix: 3706643 - remove irrelevant code.

ArgusWeb/app/js/controllers/alerts.js, ArgusWeb/app/js/controllers/dashboards.js, ArgusWeb/app/js/directives/tableTabs.js, ArgusWeb/app/js/services/storage.js, ArgusWeb/app/js/services/tableListService.js, ArgusWeb/app/js/templates/alert-list.html, ArgusWeb/app/js/templates/dashboard-list.html, ArgusWeb/app/js/templates/tableTabs.html
- Created a new tab for admin/privileged users to view other users' private items
- Refactored some directives and controller (no more $scope.shared)
To test: login as a privileged user and you will see a new in the list view. Click it and you should be able to see other people's private items.
=> New tab for admin/privileged users in the list view

ArgusWeb/app/css/main.css, ArgusWeb/app/index.html, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/directives/modals/chartOptions.js, ArgusWeb/app/js/templates/charts/topToolbar.html, ArgusWeb/app/js/templates/modals/chartOptions.html
=> add modal for chart options

ArgusCore/pom.xml, ArgusCore/src/main/java/com/salesforce/dva/argus/entity/MetricSchemaRecordQuery.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/DiscoveryService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/MonitorService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/SchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/cache/RedisCacheService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AsyncHbaseSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/DefaultDiscoveryService.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/DefaultDiscoveryServiceTest.java, ArgusWeb/src/main/docker/Dockerfile, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/DiscoveryResources.java
This includes the Docker file update to remove bower instruction.
=> update 3-1 with develop

ArgusWeb/app/css/main.css, ArgusWeb/app/index.html, ArgusWeb/app/js/argus.js, ArgusWeb/app/js/directives/charts/table.js, ArgusWeb/app/js/services/agTableService.js, ArgusWeb/app/js/templates/ag-table.html, ArgusWeb/app/js/utils/filters.js
- Pagination with truncation
- Search feature
- Sort across row
- Scrollable table area
- Fixed header for top row and left column
- Support ag-option title.text
- No need to have itemsPerpage in ag-option because user can interactively set that 
- Option storage for the table
=> Add new ag-table 

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/charts/topToolbar.html, ArgusWeb/app/js/templates/modals/chartOptions.html
- moved Synchronize charts to modal
- enabled color palette options to work and update local storage
- minor html, css tweaks.
whats left?
- reset options
- apply to all charts
=> chart options modal update

ArgusWeb/app/css/main.css, ArgusWeb/app/index.html, ArgusWeb/app/js/argus.js, ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/chartRendering.js, ArgusWeb/app/js/templates/charts/topToolbar.html, ArgusWeb/app/js/templates/viewmetrics.html, ArgusWeb/app/package.json, ArgusWeb/webpack_index.html
Turn a chart in dashboard or view metric page to full-screen mode.
=> Add full screen mode for charts

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/statusIndicator.js, ArgusWeb/app/js/services/charts/chartRendering.js, ArgusWeb/app/js/services/utilService.js, ArgusWeb/app/js/templates/viewmetrics.html, ArgusWeb/webpack_index.html
- Fix the bug of unable to detect 0 value
- Fix the bug of name field does not support period characters
=> Fix a few bugs related to status indicator

ArgusClient/src/main/java/com/salesforce/dva/argus/client/AnnotationCommitter.java, ArgusClient/src/main/java/com/salesforce/dva/argus/client/MetricCommitter.java, ArgusClient/src/main/java/com/salesforce/dva/argus/client/SchemaCommitter.java, ArgusCore/src/main/java/com/salesforce/dva/argus/entity/History.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/GOCNotifier.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/history/HBaseHistoryService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/FillCalculateTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/HoltWintersAnalysis.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricFilterWithInteralReducerTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricReducerOrMappingWithConstantTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/NormalizeTransformWrap.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/monitor/DefaultMonitorService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/mq/kafka/Producer.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AsyncHbaseSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/HbaseSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/CachedTSDBService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/DefaultTSDBService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/PhoenixTSDBEngine.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/warden/DefaultWardenService.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/PercentileTransformTest.java
Mostly minor things in code comments and strings in error messages. If anything looks incorrect let me know and I'm happy to change.
=> Fix a couple of typos and spelling errors

ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/modals/chartOptions.html
spelling change. no changes to functionality.
=> lets spell palette correctly!

ArgusClient/src/main/java/com/salesforce/dva/argus/client/AnnotationCommitter.java, ArgusClient/src/main/java/com/salesforce/dva/argus/client/MetricCommitter.java, ArgusClient/src/main/java/com/salesforce/dva/argus/client/SchemaCommitter.java, ArgusCore/src/main/java/com/salesforce/dva/argus/entity/History.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/GOCNotifier.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/history/HBaseHistoryService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/FillCalculateTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/HoltWintersAnalysis.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricFilterWithInteralReducerTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricReducerOrMappingWithConstantTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/NormalizeTransformWrap.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/monitor/DefaultMonitorService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/mq/kafka/Producer.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AsyncHbaseSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/HbaseSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/CachedTSDBService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/DefaultTSDBService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/PhoenixTSDBEngine.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/warden/DefaultWardenService.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/PercentileTransformTest.java, ArgusWeb/app/js/config.js, ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/directives/modals/chartOptions.js, ArgusWeb/app/js/templates/modals/chartOptions.html, ArgusWeb/app/js/templates/viewmetrics.html
=> Correct spelling for release branch

ArgusWeb/app/.eslintrc.json, ArgusWeb/app/js/controllers/alertsDetail.js, ArgusWeb/app/js/templates/alert-detail.html, ArgusWeb/app/js/utils/filters.js, ArgusWeb/app/package.json
minor changes this sprint:
- only a few minor lint changes. more to come in next sprint.
- fix bug related to trigger disassociate issue.
- change security level input to menu.
- add textarea for custom text in notification.
=> Merge sprint branch ui-3-2 into develop

ArgusWeb/app/index.html, ArgusWeb/app/js/argus.js, ArgusWeb/app/js/directives/UItools/ngConfirm.js, ArgusWeb/app/js/directives/modals/confirmClick.js, ArgusWeb/app/js/templates/alert-detail.html, ArgusWeb/app/js/templates/batches.html, ArgusWeb/app/js/templates/modals/chartOptions.html, ArgusWeb/app/js/templates/modals/confirmClick.html, ArgusWeb/app/js/templates/tableList.html
Replace all ng-confirms with confirm modal, affected items:
- clone&delete of Dashboards, Alerts
- delete of triggers
- delete of notificatoins
- reset of chart options
- delete of batch
=> Add confirm modal

ArgusWeb/app/js/controllers/alertsDetail.js, ArgusWeb/app/js/controllers/batches.js, ArgusWeb/app/js/controllers/dashboards.js, ArgusWeb/app/js/controllers/dashboardsDetail.js, ArgusWeb/app/js/controllers/login.js, ArgusWeb/app/js/controllers/main.js, ArgusWeb/app/js/controllers/metricElements.js, ArgusWeb/app/js/controllers/namespace.js, ArgusWeb/app/js/controllers/viewElements.js, ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/directives/breadcrumbs.js, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/flags.js, ArgusWeb/app/js/directives/charts/heatmap.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/directives/charts/metric.js, ArgusWeb/app/js/directives/charts/option.js, ArgusWeb/app/js/directives/charts/statusIndicator.js, ArgusWeb/app/js/directives/charts/table.js, ArgusWeb/app/js/directives/modals/confirmClick.js, ArgusWeb/app/js/services/charts/chartElements.js, ArgusWeb/app/js/services/charts/chartTools.js
down to letter 'a' in filename.  about 5-6 files to go.
=> more updates to lint changes & fixes. only a few files to go.

ArgusWeb/app/css/main.css, ArgusWeb/app/index.html, ArgusWeb/app/js/argus.js, ArgusWeb/app/js/directives/controls/select.js, ArgusWeb/app/package.json, ArgusWeb/webpack_index.html
- similar use with ag-text and other control directive
- support keyword search/auto completion
- generate a scroll bar when options are of large number
- use option tag inside it to define the options text and values
Will add support for infinite scroll when using api to add the options for scenarios like filling the field in metric discovery.
=> Add ag-select directive

ArgusWeb/app/js/argus.js, ArgusWeb/app/js/argusConfig.js, ArgusWeb/app/js/config.js, ArgusWeb/app/js/controllers/about.js, ArgusWeb/app/js/controllers/admin.js, ArgusWeb/app/js/controllers/alerts.js, ArgusWeb/app/js/directives/controls/select.js, ArgusWeb/app/js/services/charts/chartElements.js
eslint still throws errors for 'indent' settings related switch statements.  Can't reconfigure or turn off. Also there is an issue with Argus.js.  File has been updated, but eslint still reporting issues.  May need to use jshint/jslint instead.. tbd.
=> finish lint updates and fixes.

ArgusCore/src/main/java/com/salesforce/dva/argus/entity/MetricSchemaRecord.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/CallbackService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/SchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/GroupByTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AsyncHbaseSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/DefaultDiscoveryService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/DefaultTSDBService.java, ArgusCore/src/main/javacc/MetricReader.jj, ArgusCore/src/test/java/com/salesforce/dva/argus/service/DefaultDiscoveryServiceTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/GroupByTransformTest.java, ArgusDocker/README.md, ArgusWeb/app/js/controllers/dashboards.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/templates/alert-detail.html, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/DiscoveryResources.java
=> Merge develop into 4-1

ArgusWeb/app/js/controllers/viewMetrics.js, ArgusWeb/app/js/templates/viewmetrics.html
=> Add GMT option on viewMetrics page

ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/storage.js
- Fix an issue that user preference is lost when logout
- Fix an issue that user preference change affect other dashboards
=> Fix some issues on user preference in local storage

ArgusWeb/app/js/config.js, ArgusWeb/app/js/controllers/dashboards.js, ArgusWeb/app/js/controllers/dashboardsDetail.js, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/chartElements.js, ArgusWeb/app/js/services/charts/chartTools.js, ArgusWeb/app/js/services/utilService.js, ArgusWeb/config/config.js
- Downsample the graphs in brush area by default since brush only shows the overview of the graphs
- Fix a few bugs related to having metrics with data and metrics without errors (color scheme and toggling not work properly)
- Cherry pick bug fix of x scale typo and version number update
=> Legend bug fixes and small performance improvement

ArgusWeb/app/index.html, ArgusWeb/app/js/argus.js, ArgusWeb/app/js/directives/modals/confirmClick.js, ArgusWeb/app/js/services/ConfirmClickService.js, ArgusWeb/app/js/services/storage.js, ArgusWeb/app/js/templates/modals/confirmClick.html, ArgusWeb/package.json, ArgusWeb/webpack.config.js
- Add modal for clearing local Storage when it is full
- Modify Storage service
- Update webpack loader for es2015 preset
=> Add modal for clearing local Storage and minor change

ArgusWeb/app/css/main.css, ArgusWeb/app/js/controllers/alerts.js, ArgusWeb/app/js/controllers/dashboards.js, ArgusWeb/app/js/controllers/dashboardsDetail.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/chartElements.js, ArgusWeb/app/js/services/factories/alerts.js, ArgusWeb/app/js/services/factories/dashboards.js
- Lazy load for dashboard list page
- Fix the bug of broken main brush
- Improve legend respond speed
=> Dashboards rendering enhancement 

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/statusIndicator.js, ArgusWeb/app/js/services/charts/chartRendering.js, ArgusWeb/app/js/services/dashboard.js, ArgusWeb/app/js/templates/headerMenu.html
remove Beta tab in header for now
=> Status Indicator improvements

ArgusCore/src/main/java/com/salesforce/dva/argus/entity/KeywordQuery.java, ArgusCore/src/main/java/com/salesforce/dva/argus/entity/MetricSchemaRecordQuery.java, ArgusCore/src/main/java/com/salesforce/dva/argus/entity/SchemaQuery.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/DiscoveryService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/SchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AbstractSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AsyncHbaseSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/CachedDiscoveryService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/DefaultDiscoveryService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/MetricSchemaRecordList.java, ArgusCore/src/test/java/com/salesforce/dva/argus/AbstractTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/TSDBServiceIT.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/AbstractSchemaServiceTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/CachedDiscoveryServiceTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/DefaultDiscoveryServiceTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/SchemaServiceIT.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/DiscoveryService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/entity/MetricDiscoveryResult.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/DiscoveryServiceTest.java, ArgusSDK/src/test/resources/DiscoveryServiceTest.json, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/dto/MetricDiscoveryQueryDto.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/dto/MetricDiscoveryResultDto.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/DiscoveryResources.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/RootResource.java
- Adding an ES based SchemaService implementation.
- SchemaService now provides a full-text keyword search method. However, AsyncHBaseSchemaService implementation does not implement this method. It will throw an UnsupportedOperationException if users try to invoke a keywordSearch on it. 
- Exposing extremely limited ES functionality in this v1 implementation.
=> ElasticSearch based schema service implementation.

ArgusWeb/app/js/templates/headerMenu.html
To be deployed to Argus Integration QA server.
=> turn Beta feature metric browsing on in the header.

ArgusWeb/app/js/config.js, ArgusWeb/app/js/services/factories/browsing.js, ArgusWeb/config/development.json, ArgusWeb/config/integration.json, ArgusWeb/config/local.json, ArgusWeb/config/production.json, ArgusWeb/config/qa.json
Commit to update config files in git.soma :
https://git.soma.salesforce.com/ArgusMonitoring/Miscellaneous/commit/6690421f5e882b1f3616c1a499b29814eb8f73e5
=> Update config files for latest info

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/chartElements.js, ArgusWeb/app/js/services/charts/chartTools.js
- Added stackbar chart 
- Fixed some issues when resize and brushing are used together with some graphs being hidden
=> Stack bar chart and some bug fixes

ArgusWeb/app/css/main.css, ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/heatmap.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/services/charts/chartElements.js, ArgusWeb/app/js/services/charts/chartTools.js, ArgusWeb/app/js/templates/charts/topToolbar.html, ArgusWeb/app/js/templates/modals/chartOptionsForHeatmap.html
- Add new directive heatmap
- Add new templates for heatmap menu option modal
Parameters for heatmap:
- aggregateType : how you aggregate the data (avg/sum)
- intervalInMinutes: Time range for a bucket ( in minutes),  aggregate data for every bucket.
- bucketMin: You can explicitly define the minimum number for y domain.
- step: Value range of data in a bucket.
- numOfBucket: How many buckets on y axis.
The default color is steel blue. You can change the heatmap color in option modal.
The parameters can be set both in ag-chart mark-up or menu option modal. The latter overwrites the former if defined.
=> Add heatmap feature

ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/lineChart.js
- Render agFlag within agChart as annotations
- Hide brush and enable mouse zoom for small charts by default
=> Add agFlag

ArgusWeb/app/js/directives/charts/heatmap.js, ArgusWeb/app/js/directives/charts/lineChart.js, ArgusWeb/app/js/directives/controls/date.js, ArgusWeb/app/js/services/charts/chartElements.js, ArgusWeb/app/js/services/charts/chartTools.js, ArgusWeb/app/js/templates/modals/chartOptionsForHeatmap.html
- Support small chart and heatmap with local time zone view
- Allow more flexible date format with small chart
- Change x axis tick numbers for regular size chart
=> Bug fixes with time zone viewing option with charts

ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/DefaultTSDBService.java
Fix /annotations endpoint returning additional data than the time range queried.
=> Fix annotations related bug.

ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/GOCNotifier.java
The maximum length for className field is 50.
=> Change className, eventName field length truncation

ArgusCore/src/main/java/com/salesforce/dva/argus/system/SystemConfiguration.java, ArgusCore/src/main/java/com/salesforce/dva/argus/system/SystemInitializer.java
To setup for onboarding Warden-as-a-Service
=> Make WardenService a configurable binding

ArgusDocker/persistent/docker-compose.yml, ArgusDocker/simple/docker-compose.yml, pom.xml
Fix #451 by setting docker org to `salesforce` org.
=> Change docker org to salesforce

ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/AlertService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/AnnotationService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/ArgusService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/AuditService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/AuthService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/BatchService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/DashboardService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/DiscoveryService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/HistoryService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/MetricService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/NamespaceService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/UserService.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/exceptions/ArgusServiceException.java, ArgusSDK/src/main/java/com/salesforce/dva/argus/sdk/exceptions/TokenExpiredException.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/AlertServiceTest.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/AnnotationServiceTest.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/AuditServiceTest.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/AuthServiceTest.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/BatchServiceTest.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/DashboardServiceTest.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/DiscoveryServiceTest.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/HistoryServiceTest.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/MetricServiceTest.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/NamespaceServiceTest.java, ArgusSDK/src/test/java/com/salesforce/dva/argus/sdk/UserServiceTest.java
We out here bringing out the cleanest quality of code
Business value: 
* Cumulative development time decrease from developers not having to do double takes when they try to pronounce `excpetions` in their head
* Marketability of SDK from the new polished look our imports in the SDK source will have
=> ArgusSDK: Spell-check 'excpetions' package to 'exceptions'

ArgusWeb/app/js/config.js, ArgusWeb/app/js/directives/controls/select.js, ArgusWeb/app/js/services/controls.js, ArgusWeb/config/config.js
- Fix the issue that url parameter for ag-select does not match the metric sent 
- Fix the issue that '+' character is not encoded in the url in view metrics page
=> Update version and fix url encoding issue

ArgusWeb/app/js/directives/charts/chart.js, ArgusWeb/app/js/directives/charts/table.js, ArgusWeb/app/js/directives/controls/date.js, ArgusWeb/app/package-lock.json, ArgusWeb/app/package.json
Update jQuery version and a few dependencies on it to remove security vulnerability
=> Update jquery dependency

ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Dashboard.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/DashboardService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/jpa/DefaultDashboardService.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/DashboardServiceTest.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/DashboardResources.java
* Added Dashboard Version Support to /dashboards API 
* Added Dashboard  Version Support to /dashboards/meta API
* Added Dashboard  Version Support to /dashboards/shared API
* Added Dashboard  Version Support to /dashboards/shared/meta API
=> Added Version Support to Dashboards API

ArgusWeb/app/js/controllers/alertsDetail.js
minor nit...it is GUS everywhere so on Argus as well :)
=> label case fix

ArgusCore/src/main/java/com/salesforce/dva/argus/service/MetricService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/TSDBService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/DefaultMetricService.java, ArgusCore/src/main/javacc/MetricReader.jj, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/filter/PerfFilter.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/MetricResources.java
- Modified approach since we don't have to make additional call to expand time series again for measurement.
=> Add qurey window and no. expanded time series as attributes from metric reader back to perffilter

ArgusWeb/app/index.html, ArgusWeb/app/js/controllers/alertsDetail.js, ArgusWeb/app/package-lock.json, ArgusWeb/package-lock.json
Also added the reference to agCompute in index.html file
=> Bug fix: unable to render alert list after edit a single alert

ArgusCore/src/main/java/com/salesforce/dva/argus/entity/Chart.java
Added support for new chart types:
BAR,
STACKED_BAR,
INDICATOR,
SCATTER_PLOT,
DISTRIBUTION_LIST,
TOP_LIST
=> Charttypes

ArgusCore/pom.xml, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/AbstractTSDBService.java
=> Tsdb load balancing

.travis.deploy.sh
@dilipdevaraj-sfdc adding absolute path to scripts / files
=> Source scripts from absolute path (${TRAVIS_BUILD_DIR}/script)

ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/MetricResources.java
=> Return 400 for invalid metric expressions

.gitignore, ArgusCore/src/main/java/com/salesforce/dva/argus/entity/MetricSchemaRecordQuery.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/MonitorService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaServiceTest.java
Change discovery service to lookup scopes index
@nkunal @dilipdevaraj-sfdc
=> Change discovery service to lookup scopes index

ArgusCore/src/main/java/com/salesforce/dva/argus/entity/OAuthAuthorizationCode.java, ArgusWeb/app/js/controllers/oauthConfirmation.js, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/dto/TokenResponseDto.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/OAuthResource.java
* TokenResponseDto has been reverted back to underscore format but not the cameCase format inorder to support the grafana expected response format.
=> Some Fixes made to support OAuth changes related to Grafana

ArgusCore/src/main/java/com/salesforce/dva/argus/entity/MetricSchemaRecordQuery.java, ArgusCore/src/main/java/com/salesforce/dva/argus/entity/ScopeAndMetricOnlySchemaRecord.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/MonitorService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/monitor/DefaultMonitorService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AbstractSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AsyncHbaseSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/MetricSchemaRecordList.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/SchemaRecordList.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ScopeAndMetricOnlySchemaRecordList.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ScopeOnlySchemaRecordList.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/CallbackServiceTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/AbstractSchemaServiceTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaServiceTest.java
PR is read to sign off.
Added unit tests.
Tested out the changes in dev cluster
=> Add new scope+metric index

ArgusClient/src/main/java/com/salesforce/dva/argus/client/SchemaCommitter.java, ArgusCore/src/main/java/com/salesforce/dva/argus/entity/MetricSchemaRecord.java, ArgusCore/src/main/java/com/salesforce/dva/argus/entity/ScopeOnlySchemaRecord.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/AlertDefinitionsCacheRefresherThread.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/SchemaRecordList.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ScopeAndMetricOnlySchemaRecordList.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ScopeOnlySchemaRecordList.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaServiceTest.java
Add 'cts' field for scopenames index
Add 'cts' field for scopemetricnames index
Fix bug with alertdefinition logging. 
Enabling using scopeandmetric.index.
=> Add 'cts' field for scopemetricnames index | Add 'cts' field for scopenames index

ArgusWeb/app/js/directives/charts/table.js, ArgusWeb/app/js/templates/ag-table.html, ArgusWeb/app/js/templates/tableList.html
- Add handling for no-data scenario
- Fix pagination info displaying issue
=>  Add handling for no-data scenario for ag-table and some other fixes

.travis.yml
do not use docker since default disk space is low on docker and builds fail.
@naveenreddykarri
=> increase disk space for build env

ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/AbstractTSDBService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/AnnotationTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/DefaultTSDBService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/ShardedTSDBService.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/tsdb/AbstractTSDBServiceTest.java
Needs more testing. Will cleanup the added debug statements.
Added unit tests. It does batching on put metrics for annotations, get is still not batched and then final add annotations which is already batched. It also maintains a LRU cache for uids that are retrieved.
=> Batch Argus Annotation uid retrieval and add caching

.travis.yml
@naveenreddykarri this will report disk usage on the build system.
=> report disk usage

ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AbstractSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/MetricSchemaRecordList.java, ArgusCore/src/main/java/com/salesforce/dva/argus/system/SystemMain.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaServiceTest.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/dto/MetricDto.java, ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/resources/CollectionResources.java
- metatags support in collections endpoint, 
- update expiration timestamp in elastic search when documents are updated
=> clean branch for metatags support and expiration timestamp update

.gitignore, ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/mail/DefaultMailService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/tsdb/AbstractTSDBService.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/CallbackServiceTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/tsdb/AbstractTSDBServiceTest.java
also catch all exceptions so that retries work. Fix bug in annotation retries.
Also added some alert code refactoring.
=> Fixes to address tsdb batch update failures

ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/notifier/RefocusNotifier.java
@rev @naveenreddykarri @sundeepsf 
tested in dev env using refocus perspective: https://refocus-sandbox.internal.salesforce.com/perspectives/ArgusQAPerspective
test alert https://argusdev-ui.data.sfdc.net/argus/#/alerts/1642354
=> RefocusNotifier: fix the sample value type

ArgusWeb/app/js/controllers/alertsDetail.js
=> remove Refocus notifier from UI

ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/AbstractSchemaService.java
@colbyguan @kow1011b  please review
=> provide config flag for bloom state file writing

ArgusCore/src/main/java/com/salesforce/dva/argus/service/alert/DefaultAlertService.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/jpa/DefaultJPAService.java
Also, removed auto-flush for JPAEntity merge operation
=> Handled case when inertia=0 for the NO_DATA trigger type. 

ArgusCore/src/main/java/com/salesforce/dva/argus/service/schema/ElasticSearchSchemaService.java
=> fix index creation on new ES cluster

ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/DivideValueReducerOrMapping.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricReducerOrMappingTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/MetricReducerOrMappingWithConstantTransform.java, ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/RangeTransformWrap.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/DeviationTransformTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/DiffTransformTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/DivideTransformTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/PercentileTransformTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/RangeTransformTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/ScaleTransformTest.java, ArgusCore/src/test/java/com/salesforce/dva/argus/service/metric/transform/SumTransformTest.java
Transform improvements - 
1. Made the #union# option to be default for SUM, SCALE, RANGE and PERCENTILE reducers.
2. Modified the divide transform to gracefully handle divide by zero case
=> Transform improvements
